### ISSUE TITLE
There is not enough remote access

### ISSUE THREAD

**Issue by intulint** [matteoserva/GraphLLM#4]
I wanted to run with win10, but the examples don't work there, the scripts are written for linux. As well as the whole project, as I guess. 
If it were possible to connect to the web interface remotely, this would not be a problem. 
I'm just writing my thoughts.

**Comment by matteoserva** [comment]
As you have guessed, the project has been developed and tested on linux.
But it should work on windows without too much trouble.

Another user in https://github.com/matteoserva/GraphLLM/issues/2 used it on windows. It should also be compatible with WSL.

The whole project can be used remotely. GraphLLM, llama.cpp and your browser can be on three different machines.
To connect GraphLLM to a remote llama.cpp, you have to edit the client_config.yml file.
To connect your browser to a remote GraphLLM instance, you have to replace localhost with the remote address in the URL.

Could you clarify what kind of error you are getting?

**Comment by intulint** [comment]
Even then I installed and launched it on another computer with Linux. But I couldn’t connect to it from another computer with win10 on the same local network. It seems like you need to think about the firewall.
There is no error as such, I just thought that the web interface is only visible locally.
